# Generated by Django 6.0.4 on 2026-04-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='operador',
            field=models.CharField(default='Sistema', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_recebido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
